### ISSUE TITLE
Chrome vs Emails with subject lines of more than 168 Characters

### ISSUE THREAD

**Issue by USB-TonYnoT** [tonyfederer/OutlookFileDrag#10] opened 2018-09-04 09:20 UTC
Drag&Dropping emails with a subject line of more than 168 Characters will not work on Chrome browsers.

Tested with:
Chrome version 68.0.3440.106 (Official Build) (64-bit)
Outlook Pro 2010
At two totally different machines/networks, Windows 10 Pro (1803) (64bit, x64) and Windows 7 Home Premium

PS. Not an issue with IE
PS. Fixing those who actually write emails with that long subject lines is outside the scope of this report... 😋

**Comment by tonyfederer** [comment] 2018-11-09 03:56
I just fixed an issue where a PathTooLong exception was generated when the temporary filename was longer than MAX_PATH (260 characters).  The filename will now be truncated if it is too long, which is typically caused by e-mails with very long subject lines.

This fix has been released in v1.0.2.

**Comment by TonyWilsonMosman** [comment] 2018-11-09 08:10
So much appreciating you taking care of this :). It work perfectly. It only truncates the filename, so it can be accepted by html5, but the actual original subject lines remains as is. Thank you 💯

**Closed as completed** 2018-11-10 01:24 UTC
Labels: bug
