### ISSUE TITLE
OutlookFileDrag causing problems in Outlook

### ISSUE THREAD

**Issue by LisaCounsell** [tonyfederer/OutlookFileDrag#9] opened 2018-08-26 22:24 UTC
Hi

We are using OutlookFileDrag and it is causing problems within Outlook. Some users are unable to drag emails to another folder or meetings from one calendar to another. Outlook will shut down. If the OutlookFileDrag is turned off these functions work as expected.

Is there an update available to fix these problems?

Kind regards
Lisa Counsell

**Comment by LisaCounsell** [comment] 2018-09-02 21:01
Hi Tony

We are running the 32-bit version of Office and a combination of outlook 2016 and 2010. We are replacing the 2010 version with 2016 so are more interested in resolving the issue for 2016.

Thank you
Lisa

**Comment by LisaCounsell** [comment] 2018-09-05 22:29
Hi Tony

I'm just following up to see if you have any more information regarding this problem.

Regards
Lisa

**Comment by tonyfederer** [comment] 2018-11-10 04:45
Please try installing the latest version of OutlookFileDrag to see if these issues persist.

**Comment by LisaCounsell** [comment] 2018-11-12 02:59
Hi Tony
I have installed this on one user's pc and she is still experiencing the same problem. I disabled the add-in in Outlook, shutdown Outlook, uninstalled the add-in, installed the latest version and re-enabled the add-in in Outlook. Have a missed anything? Is there any way to determine that Outlook is using the latest version?
Cheers Lisa

**Comment by LisaCounsell** [comment] 2018-11-13 20:06
Hi Tony
I have tried this new version with another user and the problem is also still occurring with this user. 

So the problems of being unable to drag and drop meetings and/or emails into folders and attachments into other applications is still causing problems.

Can you please let me know the timing of getting another update for this?

Kind regards
Lisa

**Comment by tonyfederer** [comment] 2018-11-14 00:34
Lisa, I have tested Outlook 2016 on several computers and have not experienced the issues you are describing when dragging e-mails or attachments.

There is a known issue where attempting to drag a calendar item will cause Outlook to crash.  To work around this issue, the add-in automatically disables the drag & drop hook whenever Outlook switches to calendar view.

Can you please attach the log file from %appdata%\OutlookFileDrag so I look into this deeper?

**Comment by LisaCounsell** [comment] 2018-11-15 02:10
Hi Tony

Here is the log file from the user that is unable to drag meeting, emails and attachments.

[OutlookFileDrag.log](https://github.com/tonyfederer/OutlookFileDrag/files/2583358/OutlookFileDrag.log)

Please let me know if you need any additional information.

Cheers
Lisa

**Comment by LisaCounsell** [comment] 2018-11-15 19:51
Hi Tony

Here is the log file from the second user who is using the new version and the drag and drop of meetings is still not working. 

[OutlookFileDrag.log](https://github.com/tonyfederer/OutlookFileDrag/files/2586787/OutlookFileDrag.log)

Cheers Lisa

**Comment by tonyfederer** [comment] 2018-11-16 01:13
Lisa, neither of the log files show any errors occurring  Can you please provide the steps to reproduce the issue?

**Comment by LisaCounsell** [comment] 2018-11-16 02:33
Hi Tony,

I will contact the user first thing on Monday and get the steps for you. Cheers Lisa

**Comment by LisaCounsell** [comment] 2018-11-19 20:04
Hi Tony, please see the attached files for the problem with dragging a meeting causing Outlook to crash. I have also attached the log file. The entries in the log file are from an hour we reproduced this so it looks like the process is not writing to the file. I have installed the latest version for two users and for one of the users the problem wasn't fixed initially (she was unable to drag meetings, emails or attachments). Then after a couple of days the problem stopped, this problem had been going on for months. Sometimes in the morning the first time she tries to drag something Outlook crashes but it works after that. Could it be possible that something needs to kick the process off?

[OutlookFileDrag.log](https://github.com/tonyfederer/OutlookFileDrag/files/2596877/OutlookFileDrag.log)
[OutlookFileDrag.docx](https://github.com/tonyfederer/OutlookFileDrag/files/2596878/OutlookFileDrag.docx)

It would be great to sort this out as we have another user who just had the older version of the add-in installed and she is experiencing problems with dragging emails and attachments. We are still installing the older version as our standard until we are sure the newer version fixes the problems.

Cheers
Lisa

**Comment by LisaCounsell** [comment] 2018-11-21 21:51
Hi  Tony, I'm following up to see if you have made any progress on this as we have another user with the same problem of not being able to drag emails into subfolders.

Cheers Lisa

**Comment by tonyfederer** [comment] 2018-11-22 04:06
Lisa, I could not find anything useful in the logs.  I created a new test version with more logging enabled and some other minor improvements.  Please install this version, delete the existing log in the %appdata%\OutlookFileDrag folder, reproduce the issue, and send me the new log file.

[OutlookFileDragSetup_x64.zip](https://github.com/tonyfederer/OutlookFileDrag/files/2606538/OutlookFileDragSetup_x64.zip)
[OutlookFileDragSetup.zip](https://github.com/tonyfederer/OutlookFileDrag/files/2606540/OutlookFileDragSetup.zip)

**Comment by LisaCounsell** [comment] 2018-11-23 00:08
Hi Tony
I have installed this version on to the user who is having problems with dragging emails to different folders.  We replicated this and I have attached the log file.

[OutlookFileDrag.log](https://github.com/tonyfederer/OutlookFileDrag/files/2609430/OutlookFileDrag.log)

Cheers
Lisa

**Comment by LisaCounsell** [comment] 2018-11-23 00:12
This is the log file from the same user who is also having problems dragging meetings and this has been replicated in this log file.

[OutlookFileDrag.log](https://github.com/tonyfederer/OutlookFileDrag/files/2609437/OutlookFileDrag.log)


Cheers Lisa

**Comment by tonyfederer** [comment] 2018-11-23 03:09
Thanks Lisa. That log file helped me narrow down the problem.  There appears to be an issue trying to get the filenames of the virtual items being dragged.

I added some more error handling around that function.  Can you please uninstall the current version, install this version, delete the log file, reproduce the issue again, and send me the new log file?

[OutlookFileDragSetup_x64.zip](https://github.com/tonyfederer/OutlookFileDrag/files/2609601/OutlookFileDragSetup_x64.zip)
[OutlookFileDragSetup.zip](https://github.com/tonyfederer/OutlookFileDrag/files/2609603/OutlookFileDragSetup.zip)

**Comment by LisaCounsell** [comment] 2018-11-23 03:13
Hi Tony, that is great news! The user has gone home for the day so I will get this for you first thing on Monday.
Lisa

**Comment by LisaCounsell** [comment] 2018-11-25 22:16
Hi Tony
I have installed the latest version on the user's pc. Here is the log file after dragging an email caused Outlook to crash.

[OutlookFileDrag.log](https://github.com/tonyfederer/OutlookFileDrag/files/2613566/OutlookFileDrag.log)

This time dragging a meeting worked (however, this has worked for her in the past for a few times and then stops working so I have asked her to let me know if it fails.) I have attached the log file anyway.

[OutlookFileDrag.log](https://github.com/tonyfederer/OutlookFileDrag/files/2613567/OutlookFileDrag.log)

**Comment by tonyfederer** [comment] 2018-11-26 01:49
Lisa,

Unfortunately the new logs did not provide any new useful information.  I added more debugging lines to try to narrow down exactly which line of code has the issue.

Can you please uninstall the current version, install this version, delete the log file, reproduce the issue again, and send me the new log file?

[OutlookFileDragSetup_x64.zip](https://github.com/tonyfederer/OutlookFileDrag/files/2613786/OutlookFileDragSetup_x64.zip)
[OutlookFileDragSetup.zip](https://github.com/tonyfederer/OutlookFileDrag/files/2613787/OutlookFileDragSetup.zip)

**Comment by LisaCounsell** [comment] 2018-11-26 02:10
Hi Tony, here you go.

[OutlookFileDrag.log](https://github.com/tonyfederer/OutlookFileDrag/files/2613843/OutlookFileDrag.log)

should the version of the application have changed as it is still showing 1.0.3
Cheers Lisa

**Comment by tonyfederer** [comment] 2018-11-27 04:43
Thanks Lisa.  I was able to narrow down the error to the exact line of code causing Outlook to crash when dragging an e-mail.  I made a correction that will hopefully fix this issue.

Can you please uninstall the current version, install this version, delete the log file, try to reproduce the issue again, and send me the new log file?

[OutlookFileDragSetup_x64.zip](https://github.com/tonyfederer/OutlookFileDrag/files/2618368/OutlookFileDragSetup_x64.zip)
[OutlookFileDragSetup.zip](https://github.com/tonyfederer/OutlookFileDrag/files/2618369/OutlookFileDragSetup.zip)

**Comment by LisaCounsell** [comment] 2018-11-27 19:41
Hi Tony
I have installed the new file and tested both email drag and meeting drag and so far both are working. I will monitor this for a couple of days as at times both did work for awhile and then they stopped working. Attached is the log file.

[OutlookFileDrag.log](https://github.com/tonyfederer/OutlookFileDrag/files/2621593/OutlookFileDrag.log)

Thanks very much for helping out with this. I will keep you posted.

Lisa

**Comment by tonyfederer** [comment] 2018-11-28 01:30
Excellent!  Please let me know if this resolves the issue and then I will include this fix in an official release.

**Comment by LisaCounsell** [comment] 2018-12-02 21:47
Hi Tony

I spoke to the user who has the latest version and dragging emails is working perfectly. However, when she drags a meeting the meeting just disappears. I have attached the log file.

[OutlookFileDrag.log](https://github.com/tonyfederer/OutlookFileDrag/files/2637447/OutlookFileDrag.log)

Cheers Lisa

**Comment by tonyfederer** [comment] 2018-12-04 03:38
There is an outstanding issue where Outlook will crash when a user attempts
to drag an item when in a calendar view.

To work around this issue, the hook of the drag drop process should
automatically stop when you are viewing a calendar and start when you ate
no longer viewing a calendar.

Can you please delete the log file, reproduce the issue, list the steps to
reproduce the issue, and attach the log file here?

On Dec 3, 2018 5:23 PM, "LisaCounsell" <notifications@github.com> wrote:

Hi Tony
I'm just following this up with you as currently I am not able to roll this
out to the other uses due to the meetings disappearing.
Cheers Lisa

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/tonyfederer/OutlookFileDrag/issues/9#issuecomment-443909298>,
or mute the thread

**Comment by LisaCounsell** [comment] 2018-12-04 19:36
Hi Tony
Here is the log file. The user just selected a meeting and dragged it to another time on the same day and the meeting disappeared. She was able to ctrl Z to put the meeting back into it's original spot. I am not able to reproduce this on my pc.

[OutlookFileDrag.log](https://github.com/tonyfederer/OutlookFileDrag/files/2645787/OutlookFileDrag.log)

Cheers Lisa

**Comment by LisaCounsell** [comment] 2018-12-04 20:22
Hi Tony, I installed the latest version onto another user's pc this morning. The email dragging is working ok for her but she is still having the problem with Outlook crashing when she tries to drag a meeting. I restarted Outlook a couple of times before trying this.

[OutlookFileDrag.log](https://github.com/tonyfederer/OutlookFileDrag/files/2645946/OutlookFileDrag.log)

I did notice something in common between the two users this morning. When they open Outlook the right click on the calendar view at the bottom of the screen and select Open in Another window. I tried this on my pc and I was immediately unable to drag meetings and Outlook crashed.

Kind regards
Lisa

**Comment by LisaCounsell** [comment] 2018-12-05 19:35
Hi Tony, I am going to be away for a week but am really keen to keep this progressing. Can you please include the following email addresses in your communication:
Kevin.loggenberg@qldc.govt.nz
andre.freixo@qldc.govt.nz

Thank you 
Lisa

**Comment by tonyfederer** [comment] 2018-12-06 05:13
I am checking into this issue.

**Comment by tonyfederer** [comment] 2018-12-11 05:09
I was able to reproduce this issue and am working on a fix.

**Comment by tonyfederer** [comment] 2018-12-13 03:51
Lisa, good news!  I believe I have fixed this issue.  Please install this version and see if it works for your users.

[OutlookFileDragSetup_x64.zip](https://github.com/tonyfederer/OutlookFileDrag/files/2674450/OutlookFileDragSetup_x64.zip)
[OutlookFileDragSetup.zip](https://github.com/tonyfederer/OutlookFileDrag/files/2674451/OutlookFileDragSetup.zip)

**Comment by LisaCounsell** [comment] 2018-12-17 00:33
Hi Tony
That is great news! I have installed this onto my pc and one other user and so far it is working. I would like to install it on at least two of the other users that are having the same problem before I close the ticket.

I'll get back to you tomorrow.
Cheers
Lisa

**Comment by LisaCounsell** [comment] 2018-12-19 22:54
Hi Tony, one of the users with the new version is getting the following error message when she tries to drag an email into our Technology One application. Would this have anything to do with the new version?

![image](https://user-images.githubusercontent.com/42723674/50253102-f91e0d80-044d-11e9-8c00-1a597308badd.png)

Cheers
Lisa

**Comment by tonyfederer** [comment] 2018-12-22 02:40
Is the user getting this error every time she drags and drops a file or
just sometimes?

**Comment by LisaCounsell** [comment] 2019-01-07 02:34
Hi Tony

I hope that you had a great Christmas. I was just on the phone to one of the users with the latest version and she is having problems with outlook crashing when she drags an email into another email as an attachment. Again this only occurs if the calendar is open in another window. I have attached the log file. for you. (the dragging of emails into subfolders and the dragging of meeting is still working well)

[OutlookFileDrag.log](https://github.com/tonyfederer/OutlookFileDrag/files/2731214/OutlookFileDrag.log)

She is also having problems when she tries to drag an email into our Technology One application. There is no error message but again outlook crashes. I will get some more details for you tomorrow.

**Comment by LisaCounsell** [comment] 2019-01-07 23:43
Hi Tony

Here are some more details regarding the problem of dragging emails into our Technology One application. I installed the previous version and this worked ok. As soon as I install the latest version it stops working. See the attached log file.

[OutlookFileDrag.log](https://github.com/tonyfederer/OutlookFileDrag/files/2734674/OutlookFileDrag.log)

As you can see from the image, I have dragged the top email into the application on the right side. The email image shows on the screen like a ghost image and after a few minutes Outlook shuts down and the email is not saved into the application on the right hand side of the screen.

![image](https://user-images.githubusercontent.com/42723674/50799831-9e881b00-1342-11e9-8941-bf4ba64a0769.png)

Would you be able to look into this urgently (and the problem I logged yesterday) as I am not able to release this new version to the rest of the staff at the moment.

Cheers
Lisa

**Comment by TonyWilsonMosman** [comment] 2019-01-08 00:12
(fyi: when trying to zero on a bug, I found it useful to a) drag&drop first on the desktop and then from there to the browser and b) try various browsers)

**Comment by LisaCounsell** [comment] 2019-01-08 01:20
Hi Tony, just checking if you need any additional information from me. Cheers Lisa

**Comment by tonyfederer** [comment] 2019-01-10 02:36
Yes, I am working on a fix for this issue.

**Comment by tonyfederer** [comment] 2019-01-10 03:11
Lisa, can you please try this version and see if this fixes the issue?  If not, please attach the log file again.

[OutlookFileDragSetup_x64.zip](https://github.com/tonyfederer/OutlookFileDrag/files/2743424/OutlookFileDragSetup_x64.zip)
[OutlookFileDragSetup.zip](https://github.com/tonyfederer/OutlookFileDrag/files/2743425/OutlookFileDragSetup.zip)

**Comment by LisaCounsell** [comment] 2019-01-10 03:14
Hi Tony

I will put this in place first thing tomorrow morning.

Cheers
Lisa

**Comment by LisaCounsell** [comment] 2019-01-10 19:35
Hi Tony

The user that I need to test this with is away until Monday so I will install this first thing on Monday on her pc.

Kind regards
Lisa

**Comment by LisaCounsell** [comment] 2019-01-14 22:14
Hi Tony
I have updated the users workstation with the new version and so far both of the problems have been fixed: dragging an email into another email and dragging into the TechOne application. 
I would like to leave this open for the rest of week so make sure the user doesn't have any other problems.

Cheers Lisa

**Comment by tonyfederer** [comment] 2019-01-16 02:03
Great!  I'm glad it's working for you so far.

**Comment by JohnRollinsDEF** [comment] 2019-01-23 09:04
Hi both,
I am running Outlook 64 bit from Office 365 and have the problem above where dragging an email from the email list into a new draft email crashes Outlook. This is from a fresh startup of Outlook without going anywhere near the Calendar.
I have downloaded and installed the version above but that hasn't fixed the problem. Attached is the log:
[OutlookFileDrag.log](https://github.com/tonyfederer/OutlookFileDrag/files/2786446/OutlookFileDrag.log)
Would you mind taking a look at this please?
Thanks,
John

**Comment by LisaCounsell** [comment] 2019-01-24 22:21
Hi Tony
Sorry for the delay in getting back to you. I've had problems getting a time with the user who has the latest version. She is till having problems dragging emails into the TechOne application. What happens now when she drags an email into this application the email doesn't save into Techone and it disappears from Outlook (the email should stay in Outlook). See the following attachment where is did not work.

[OutlookFileDrag.log](https://github.com/tonyfederer/OutlookFileDrag/files/2793860/OutlookFileDrag.log)


I installed the older version that most people use and this works - see the following attachment.

[OutlookFileDrag.log](https://github.com/tonyfederer/OutlookFileDrag/files/2793857/OutlookFileDrag.log)

Please let me know how you get on with this and if you need any additional information.

Lisa

**Comment by tonyfederer** [comment] 2019-01-25 02:37
Ok, I will investigate this further.

**Comment by LisaCounsell** [comment] 2019-01-29 20:44
Hi Tony

Sorry for the delay in getting back to you. I still haven’t been able to make a time with the user to install the latest version. I will let you know as soon as I have done this.

Cheers
Lisa

**Comment by locvuwp2011** [comment] 2019-01-30 08:31
> Lisa, please try this version to see if it solves your latest issue.
> 
> [OutlookFileDragSetup_x64.zip](https://github.com/tonyfederer/OutlookFileDrag/files/2799765/OutlookFileDragSetup_x64.zip)
> [OutlookFileDragSetup.zip](https://github.com/tonyfederer/OutlookFileDrag/files/2799766/OutlookFileDragSetup.zip)

Hi @tonyfederer ,

I downloaded your latest installations, and it fix the issues. Could you please commit the changes that you have been made for these fix ? Because I need to up to date resource in my local.

Best Regards

**Comment by tonyfederer** [comment] 2019-01-31 00:55
Version 1.0.8 has been released and includes a fix for this issue.

- [Download for 64-bit Windows (Outlook 32-bit or 64-bit)](https://github.com/tonyfederer/OutlookFileDrag/files/2815210/OutlookFileDragSetup_x64.zip)
- [Download for 32-bit Windows](https://github.com/tonyfederer/OutlookFileDrag/files/2815211/OutlookFileDragSetup.zip)

**Comment by LisaCounsell** [comment] 2019-01-31 01:04
Great, thank you. I will let you know as soon as I have installed this.

Cheers
Lisa

**Comment by tonyfederer** [comment] 2019-02-12 01:48
Lisa, did you ever get a chance to install the latest version and confirm if this issue is resolved?

**Comment by LisaCounsell** [comment] 2019-02-12 01:52
Hi Tony

Ironically I just managed to get it installed today! We ran a test and the email is now saving in the application but is still being removed from Outlook.

I’m just about to log on and get the log file to send to you.

Cheers
Lisa

**Comment by LisaCounsell** [comment] 2019-02-12 01:56
Hi Tony

Here is the log file. Please let me know if you need anything else.

Lisa

**Comment by tonyfederer** [comment] 2019-02-12 03:07
Lisa, can you please try the latest version (1.0.10)?  Version 1.0.9 fixes the issue where items are deleted after dragging to another application and version 1.0.10 fixes a bug that was introduced in version 1.0.8.

https://github.com/tonyfederer/OutlookFileDrag/releases/tag/v1.0.10

**Comment by LisaCounsell** [comment] 2019-02-12 03:08
Hi Tony

Sorry I didn’t realise there was a later version. I will install this tomorrow.

Lisa

**Comment by tonyfederer** [comment] 2019-02-19 01:11
Lisa, can you please try version 1.0.10 and see if this resolves your issue?

**Comment by LisaCounsell** [comment] 2019-02-20 20:05
Hi Tony

Sorry for the delay in replying to you, I have been on a training course all week and so has the user that I gave this version to.

I will follow up with her later today once she has had time to catchup.

Cheers
Lisa

**Comment by LisaCounsell** [comment] 2019-02-26 00:23
Hi Tony

The user has confirmed that the issue is now resolved.

Thank you for your help with getting this sorted out.

Lisa

**Comment by tonyfederer** [comment] 2019-02-26 01:08
Great!  Thanks for all your help testing different versions.

**Closed by tonyfederer** 2019-02-26 01:08 UTC
Labels: bug
