### ISSUE TITLE
Microsoft Edge drop

### ISSUE THREAD

**Issue by Akkerb** [tonyfederer/OutlookFileDrag#8] opened 2018-08-22 08:00 UTC
Drop functionality doesn't work in Microsoft Edge browser windows with a page allowing files to drop. Same page on Chrome and firefox is working fine. Tried the 32 and 64 bit application. Any idea's?

**Comment by TonyWilsonMosman** [comment] 2018-08-28 09:34
It works for me with our Microsoft Edge 42 from Office 2010 on Windows 10 Pro

**Comment by Akkerb** [comment] 2018-09-03 06:11
Microsoft Edge 42.17134.1.0.

When I try to drop (when I hoover over Edge) I get an Enveloppe icon and cannot drop.



  [iT2 Website] <http://www.it2.nl>
BRAM VAN DEN AKKER
Email:  Bram@iT2.nl
Telefoon:       +31(0)413-490888
Direct: +31(0)73-7119007


[QR Code]
[Twitter]<https://twitter.com/it2_ict>  [LinkedIn] <https://www.linkedin.com/company/262150>
[Facebook]<https://www.facebook.com/it2schijndel>       [Google Plus] <https://plus.google.com/109124394936739711193/>

[Youtube]<https://youtu.be/zuFgQBKPVqo>
        iT takes 2<https://youtu.be/zuFgQBKPVqo> - 1 can have ambition, 2 can make it happen<https://youtu.be/zuFgQBKPVqo>



Van: Tony Federer [mailto:notifications@github.com]
Verzonden: zaterdag 1 september 2018 15:22
Aan: tonyfederer/OutlookFileDrag <OutlookFileDrag@noreply.github.com>
CC: Bram van den Akker <Bram@it2.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [tonyfederer/OutlookFileDrag] Microsoft Edge drop (#8)


Can you please provide what version of Microsoft Edge you have installed?

**Comment by esicouret** [comment] 2018-09-08 00:10
same issue here.  Can drag and drop to Chrome with no problems.  Does not work with Edge version 38.14393.1066.0

**Comment by esicouret** [comment] 2018-09-14 17:39
Hope this helps. I'm attaching 2 log files.  One was taken when dragging a PDF file from Outlook 2016 to Chrome (worked) and the other from O2016 to Edge (didn't work).

[PDF_dnd_to_chrome.log](https://github.com/tonyfederer/OutlookFileDrag/files/2384318/PDF_dnd_to_chrome.log)
[PDF_dnd_to_edge.log](https://github.com/tonyfederer/OutlookFileDrag/files/2384319/PDF_dnd_to_edge.log)

**Comment by tonyfederer** [comment] 2018-10-17 01:30
Thanks for attaching the log files.  I cannot reproduce this issue using Outlook 2016 (64-bit) and Edge 42.17134.  Can you please update your Edge browser and see if this problem still exists?

**Comment by tonyfederer** [comment] 2018-11-10 01:46
I am closing this issue.  @TonyWilsonMosman and I are unable to reproduce using Edge 42.  Users experiencing this issue should update Edge to the latest version.

**Closed by tonyfederer** 2018-11-10 01:46 UTC
